import type { Metadata, Viewport } from "next";
import { Fraunces, Poppins } from "next/font/google";

import NextTopLoader from "nextjs-toploader";

import "./globals.css";
import { AnnouncementBar } from "@/components/layout/announcement-bar";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { CouponTab } from "@/components/layout/coupon-tab";
import { CartDrawer } from "@/components/cart/cart-drawer";
import { siteConfig } from "@/lib/site-config";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  variable: "--font-fraunces",
  display: "swap",
});

export const viewport: Viewport = {
  themeColor: "#FC8EAC",
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: `${siteConfig.name} — ${siteConfig.tagline}`,
    template: `%s · ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    "Haladini",
    "block print",
    "bedsheets",
    "cushions",
    "suits",
    "shirts",
    "handcrafted",
    "Jaipur",
    "home decor",
    "Indian fashion",
  ],
  authors: [{ name: "Haladini" }],
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: `${siteConfig.name} — ${siteConfig.tagline}`,
    description: siteConfig.description,
    // OG image is generated by app/opengraph-image.tsx (file convention)
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} — ${siteConfig.tagline}`,
    description: siteConfig.description,
  },
  // Favicon resolved from app/icon.svg (file convention)
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${fraunces.variable}`}>
      <body className="min-h-screen bg-canvas">
        <NextTopLoader
          color="#F76C9C"
          height={3}
          showSpinner={false}
          shadow="0 0 10px #F76C9C,0 0 5px #F76C9C"
        />
        <AnnouncementBar />
        <Header />
        <main className="min-h-[60vh]">{children}</main>
        <Footer />
        <CouponTab />
        <CartDrawer />
      </body>
    </html>
  );
}
