// Bake a downscaled copy of the logo into a base64 data-URI TS module so the
// edge OG route can embed it without filesystem/font issues (works on Netlify).
//
// Run: node scripts/make-og-logo.mjs
import sharp from "sharp";
import { writeFileSync } from "node:fs";

const buf = await sharp("public/haladini-logo.png")
  .resize({ width: 820 })
  .png({ quality: 90 })
  .toBuffer();

const dataUri = `data:image/png;base64,${buf.toString("base64")}`;
const out = `// AUTO-GENERATED by scripts/make-og-logo.mjs — do not edit by hand.
// Downscaled Haladini logo as a data URI for the Open Graph image.
export const ogLogo =
  "${dataUri}";
`;
writeFileSync("app/og-logo-data.ts", out);
console.log(
  `Wrote app/og-logo-data.ts (${(dataUri.length / 1024).toFixed(0)} KB base64)`
);
